-- Profile/CV brain schema.
-- Matches packages/shared-types/src/profile/database.ts exactly.
-- All IDs are auto-generated integers (GENERATED BY DEFAULT AS IDENTITY).
-- No i18n jsonb here — text fields are plain text, resolved at the API layer.

-- about: singleton row with short/long bio and target roles.
create table public.about (
  id integer primary key generated by default as identity,
  bio_short text,
  bio_long text,
  target_roles text[] not null default '{}',
  is_generated boolean not null default false,
  updated_at timestamptz not null default now()
);

comment on table public.about is
  'Singleton "about me" row. bio_short is the tagline, bio_long the full narrative.';

-- experience ("work")
create table public.experience (
  id integer primary key generated by default as identity,
  title text not null,
  company text not null,
  employment_type text,
  location text,
  location_type text,
  description text,
  achievements text[] not null default '{}',
  start_date date not null,
  end_date date,
  display_order integer not null default 0,
  is_public boolean not null default true,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- qualifications (education + certificates merged)
create table public.qualifications (
  id integer primary key generated by default as identity,
  title text not null,
  issuer text not null,
  type text not null,
  description text,
  credential_id text,
  credential_url text,
  issue_date date not null,
  expiry_date date,
  display_order integer not null default 0,
  is_public boolean not null default true,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.qualifications is
  'Merged education + certificates. type distinguishes them (e.g. "degree", "certificate", "course").';

-- projects: portfolio showcase entries (part of the CV/profile brain)
create table public.projects (
  id integer primary key generated by default as identity,
  title text not null,
  type text,
  status text not null default 'completed',
  description text,
  highlights text[] not null default '{}',
  repo_url text,
  demo_url text,
  start_date date,
  end_date date,
  display_order integer not null default 0,
  is_public boolean not null default true,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- skills
create table public.skills (
  id integer primary key generated by default as identity,
  name text not null,
  category text not null,
  competency_level text,
  years_of_experience numeric,
  description text,
  display_order integer not null default 0,
  is_public boolean not null default true
);

-- junction tables: many-to-many between entities and skills
create table public.experience_skills (
  experience_id integer not null references public.experience(id) on delete cascade,
  skill_id integer not null references public.skills(id) on delete cascade,
  primary key (experience_id, skill_id)
);

create table public.project_skills (
  project_id integer not null references public.projects(id) on delete cascade,
  skill_id integer not null references public.skills(id) on delete cascade,
  primary key (project_id, skill_id)
);

create table public.qualification_skills (
  qualification_id integer not null references public.qualifications(id) on delete cascade,
  skill_id integer not null references public.skills(id) on delete cascade,
  primary key (qualification_id, skill_id)
);

-- api_keys: access control for the universal API (apps/api-profile).
create table public.api_keys (
  id uuid primary key default gen_random_uuid(),
  key_hash text not null unique,
  client_name text not null,
  revoked_at timestamptz,
  last_used_at timestamptz,
  created_at timestamptz not null default now()
);

comment on table public.api_keys is
  'service_role-only. sha-256 hashes of API keys used by apps/api-profile.';

-- indexes
create index experience_display_order_idx on public.experience (display_order);
create index qualifications_display_order_idx on public.qualifications (display_order);
create index projects_display_order_idx on public.projects (display_order);
create index skills_display_order_idx on public.skills (display_order);
create index api_keys_key_hash_idx on public.api_keys (key_hash);

-- public views: filter is_public = true, exclude notes (internal field)
create view public.v_experience as
  select id, title, company, employment_type, location, location_type,
         description, achievements, start_date, end_date, display_order,
         is_public, created_at, updated_at
  from public.experience
  where is_public = true;

create view public.v_projects as
  select id, title, type, status, description, highlights,
         repo_url, demo_url, start_date, end_date, display_order,
         is_public, created_at, updated_at
  from public.projects
  where is_public = true;

create view public.v_qualifications as
  select id, title, issuer, type, description, credential_id, credential_url,
         issue_date, expiry_date, display_order,
         is_public, created_at, updated_at
  from public.qualifications
  where is_public = true;

create view public.v_skills as
  select id, name, category, competency_level, years_of_experience,
         description, display_order
  from public.skills
  where is_public = true;
